utility to generate dummy data
foxpass/foxpass-tools pull request #34
Opened 2021-04-21 06:25 UTC by asakapab0i

## Description of the change

> Description here

## Type of change
- [ ] Bug fix
- [x] New feature

### Testing

- [ ] Testing information has been added - test cases checklist and steps followed for testing.
- [ ] Testing screenshot(s) attached for more information.

## Security

- [ ] This PR has security related considerations.

2021-04-21 07:04 UTC, ttheune requested changes
Looks good.

2021-04-21 07:23 UTC, ttheune approved these changes
looks good

2021-04-21 22:48 UTC, danishfoxpass commented
@asakapab0i i have updated the PR with required changes. You can test and merge.

2021-04-21 22:49 UTC, danishfoxpass approved these changes

2021-04-22 03:35 UTC, asakapab0i commented on api/foxpass_dummy_data.py
> +        return str(getattr(fake, cf)())
This is cool, I've looking for something like this.

2021-04-22 04:13 UTC, asakapab0i reviewed
Looks good, tested.

2021-04-22 04:14 UTC, merged